version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: notes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: notes_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      JDBC_CONNECTION_URL: ${JDBC_CONNECTION_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db